<?php
function hook_router_menu_get_item_alter(&$router_item, $path, $original_map) {
  if (user_is_logged_in()  && !($original_map[0] === "obfmobileapi" || $original_map[0] === "page_redirect" || $original_map[0] === "user" || $original_map[0] === "app_link_custom" || $original_map[0] === "page_export_user" || $original_map[0] === "page_export_observation" )) {
    global $user;
    $account = user_load($user->uid);
    if (in_array('authenticated user', array_values($user->roles)) && !(in_array('administrator', array_values($user->roles) )) ) {
      $router_item['access_callback'] = FALSE;
    }
  }
}