<?php
/**
 * Implements hook_mail_alter(&$message).
 */
function alter_personnal_form_mail_alter(&$message) {
    // dpm($message['params']);
    $deepLink = '<a href="obfmobile://home">Open my app</a>';
    $parametres = $message['params'];
    if (is_array($message['body'])) {
         $message['body'][] = $deepLink;
        // foreach ($parametres as $key => $value) {
        //     dpm($key);
        //     if($key === 'recipient'){
        //         $message['body'][] = "uid : ".$value->uid;
        //         $message['body'][] .= " created : ".$value->created;
        //     }
        //     if($key === 'form_token'){
        //         $message['body'][] .= " form_token : ".$value;
        //     }
        //     if($key === 'form_id'){
        //         $message['body'][] .= " form_id : ".$value;
        //     }
        //     // dpm($value);
        // }

    }
    else {
        // Some modules use the body as a string, erroneously.
        $message['body'] .= $deepLink;
    }
}