<?php
/**
* see https://api.drupal.org/api/examples/page_example%21page_example.module/7
*/

/**
 * Implements hook_permission().
 *
 * Since the access to our new custom pages will be granted based on
 * special permissions, we need to define what those permissions are here.
 * This ensures that they are available to enable on the user role
 * administration pages.
 */
function page_redirect_permission() {
  return array(
    'access simple page' => array(
      'title' => t('Access redirect page'),
      'description' => t('Allow users to access redirect page'),
    )
  );
}

/**
  * @see hook_menu()
 * @see menu_example
 */
function page_redirect_menu() {

  // This is the minimum information you can provide for a menu item. This menu
  // item will be created in the default menu, usually Navigation.
  $items['page_redirect'] = array(
    'title' => '',
    'page callback' => 'page_redirect_description',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  return $items;
}

/**
 * Constructs a descriptive page.
 *
 * Our menu maps this function to the path 'page_redirect'.
 */
function page_redirect_description() {
  global $user;
  $site_name = token_replace('[site:name]');

  if($user->uid === 0){
    $user->mail = "";
  }
  return array(
    '#markup' =>
      '<div><img class="img-responsive" src="./sites/all/modules/custom/page_redirect/images/observatoire-de-la-biodiversite-des-forets-01.jpg" alt="logo OBF"/></div>'.
      t('<p class="text-center">
      Congratulation!
      You can use your new password to log in on the @site_name application with your email @user_email.
      </p>',
      array(
        '@user_email' => $user->mail,
        '@site_name' => $site_name
      )
    ),
  );
}

/**
 * Implements hook_block_info_alter().
 */
function page_redirect_block_info_alter(&$blocks, $theme, $code_blocks) {
  $blocks['system']['powered-by']['status'] = 0;
}

/**
 * Hide navbar to page_redirect.
 */
drupal_add_css('.page-page-redirect #navbar {
                  display:none;
                }'
, 'inline');